# Generated by Django 4.1 on 2024-07-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tskhandler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskalloca',
            name='time',
        ),
        migrations.AlterField(
            model_name='taskalloca',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
