# Generated by Django 4.1 on 2024-07-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tskhandler', '0007_remove_taskalloca_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskalloca',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
