# Generated by Django 4.1 on 2024-07-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tskhandler', '0008_alter_taskalloca_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskalloca',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
